name: D1 Migrate Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

jobs:
  migrate-prod:
    runs-on: ubuntu-latest
    name: D1 Migrate Prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: D1 Migrate Prod
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: ${{ vars.WRANGLER_VERSION }}
          apiToken: ${{ secrets.CF_D1_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID}}
          workingDirectory: ''
          packageManager: npm
          environment: prod
          command: d1 migrations apply D1 --remote
